{
 "title": "Pizza Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Logging",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{component=\"jwt-pizza-service\"} |= `` | json"
    }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "rate(totalRequests_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "total"
    },
    {
     "expr": "rate(getRequests_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "GET"
    },
    {
     "expr": "rate(putRequests_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "PUT"
    },
    {
     "expr": "rate(postRequests_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "POST"
    },
    {
     "expr": "rate(deleteRequests_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "DELETE"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "rate(avgLatencyMs_milliseconds_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Request Latency (ms)"
    }
   ]
  },
  {
   "title": "Authentications",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "rate(successfulAuthentications_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "SuccessfulAuths"
    },
    {
     "expr": "rate(failedAuthentications_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "FailedAuths"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "activeUsers_total{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pizzas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "rate(pizzasSold_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Pizza Purchases"
    },
    {
     "expr": "rate(creationFailures_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Purchase Failures"
    }
   ]
  },
  {
   "title": "Pizza Creation Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "rate(creationLatencyMs_milliseconds_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Pizza Latency"
    }
   ]
  },
  {
   "title": "Revenue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(revenueGenerated_USD_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Revenue"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memoryPercentage_percent_total{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpuPercentage_percent_total{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}